env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    binary: cleaning-twtl
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
archives:
    -
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      format: binary
