[TwitterService]
APIKey = ""
APISecretKey = ""
AccessToken = ""
AccessTokenSecret = ""

[Twitter]
BlockIfFollowing = false
MaxFollowers = 10000
MaxFFRatio = 0.5
SearchWords = [
  "",
]
ExcludeUsers = [
  "",
]
