[TwitterService]
APIKey = ""
APISecretKey = ""
AccessToken = ""
AccessTokenSecret = ""

[Twitter]
BlockIfFollowing = false
MaxFollowers = 10000
MaxFFRatio = 0.5
SearchWords = [
  "",
]
ExcludeUsers = [
  "",
]
TweetTextFormat = """
@TOS
新規ブロック数: {% newBlockCount %}
昨日からの増加: {% increaseCount %}

{% nowDateTime %}
"""
